version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: notes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notes
      MYSQL_PASSWORD: notespass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: notes-jdk21
    container_name: notes-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notesdb
      SPRING_DATASOURCE_USERNAME: notes
      SPRING_DATASOURCE_PASSWORD: notespass

volumes:
  mysql-data:
